import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Fundo from "@/components/fundo";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Splash+yard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="pt-BR">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <Navbar></Navbar>
          <Fundo></Fundo>
          {children}
        </body>
      </html>
      <footer className="bg-gray-800 text-green-300 py-4 px-3 mt-16">
        <div className="container mx-auto flex items-center justify-between">
          {/* Esquerda */}
          <div className="w-1/3 text-left">
            <p>Caio Rodger Elias</p>
          </div>
          {/* Centro */}
          <div className="w-1/3 flex justify-center">
            <img
              className="w-40 h-32"
              src="/reis.png"
              alt=""
            />
          </div>
          {/* Direita */}
          <div className="w-1/3 text-right">
            <p>Gabriel Miranda Hipólito</p>
          </div>
        </div>
      </footer>
    </>
  );
}
